# 开发环境配置
spring:
  thymeleaf:
    cache: false
    # prefix: templates
    # suffix: .html
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      localedb:
        username: myesb
        password: myesb
        driver-class-name: com.mysql.cj.jdbc.Driver
        # driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://10.68.15.8:3306/myesb?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
      mesplat:
        url: jdbc:oracle:thin:@10.68.15.7:1521/mesplat
        username: mesif
        password: mesif
        # driver-class-name: oracle.jdbc.driver.OracleDriver
        driver-class-name: oracle.jdbc.OracleDriver
    # dynamic:
    #   primary: esb #设置默认的数据源或者数据源组,默认值即为master
    #   #lazy: false #默认立即初始化数据源，true则支持在需要建立连接时再初始化数据源
    #   #strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
    #   datasource:
    #     esb:
    #       username: myesb
    #       password: myesb
    #       # driver-class-name: com.mysql.cj.jdbc.Driver
    #       driver-class-name: com.mysql.jdbc.Driver
    #       url: jdbc:mysql://10.68.15.8:3306/myesb?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    #     mesplat:
    #       url: jdbc:oracle:thin:@10.68.15.7:1521/mesplat
    #       username: mesif
    #       password: mesif
    #       # driver-class-name: oracle.jdbc.driver.OracleDriver
    #       driver-class-name: oracle.jdbc.OracleDriver
  #        oracle:
  #          username: root
  #          password: 123456
  #          driver-class-name: oracle.jdbc.driver.OracleDriver
  #          url: jdbc:oracle:thin:@localhost:1521/bjev_project
  #        sqlServer:
  #          username: sa
  #          password: 123456
  #          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  #          url: jdbc:sqlserver://localhost:1433;databaseName=bjev_project
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒

file:
  #文件上传目录 绝对路径 末尾请加 /
  path: D:/files/ #windows
  #path: /data/files/ #linux
  #文件预览、下载的url, 末尾请勿加 /
  url: http://localhost:8080/files
